/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppContatosRouteImport } from './routes/_authenticated/app.contatos'
import { Route as AuthenticatedAppCampanhasRouteImport } from './routes/_authenticated/app.campanhas'
import { Route as AuthenticatedAppAgentesRouteImport } from './routes/_authenticated/app.agentes'
import { Route as AuthenticatedAppCampanhasNovaRouteImport } from './routes/_authenticated/app.campanhas_.nova'
import { Route as AuthenticatedAppCampanhasIdRouteImport } from './routes/_authenticated/app.campanhas_.$id'
import { Route as AuthenticatedAppAgentesIdRouteImport } from './routes/_authenticated/app.agentes_.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContatosRoute =
  AuthenticatedAppContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasRoute =
  AuthenticatedAppCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgentesRoute = AuthenticatedAppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCampanhasNovaRoute =
  AuthenticatedAppCampanhasNovaRouteImport.update({
    id: '/campanhas_/nova',
    path: '/campanhas/nova',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampanhasIdRoute =
  AuthenticatedAppCampanhasIdRouteImport.update({
    id: '/campanhas_/$id',
    path: '/campanhas/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgentesIdRoute =
  AuthenticatedAppAgentesIdRouteImport.update({
    id: '/agentes_/$id',
    path: '/agentes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agentes': typeof AuthenticatedAppAgentesRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/contatos': typeof AuthenticatedAppContatosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/agentes/$id': typeof AuthenticatedAppAgentesIdRoute
  '/app/campanhas/$id': typeof AuthenticatedAppCampanhasIdRoute
  '/app/campanhas/nova': typeof AuthenticatedAppCampanhasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agentes': typeof AuthenticatedAppAgentesRoute
  '/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/app/contatos': typeof AuthenticatedAppContatosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/agentes/$id': typeof AuthenticatedAppAgentesIdRoute
  '/app/campanhas/$id': typeof AuthenticatedAppCampanhasIdRoute
  '/app/campanhas/nova': typeof AuthenticatedAppCampanhasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agentes': typeof AuthenticatedAppAgentesRoute
  '/_authenticated/app/campanhas': typeof AuthenticatedAppCampanhasRoute
  '/_authenticated/app/contatos': typeof AuthenticatedAppContatosRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/agentes_/$id': typeof AuthenticatedAppAgentesIdRoute
  '/_authenticated/app/campanhas_/$id': typeof AuthenticatedAppCampanhasIdRoute
  '/_authenticated/app/campanhas_/nova': typeof AuthenticatedAppCampanhasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/agentes'
    | '/app/campanhas'
    | '/app/contatos'
    | '/app/relatorios'
    | '/app/'
    | '/app/agentes/$id'
    | '/app/campanhas/$id'
    | '/app/campanhas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/agentes'
    | '/app/campanhas'
    | '/app/contatos'
    | '/app/relatorios'
    | '/app'
    | '/app/agentes/$id'
    | '/app/campanhas/$id'
    | '/app/campanhas/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/agentes'
    | '/_authenticated/app/campanhas'
    | '/_authenticated/app/contatos'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/'
    | '/_authenticated/app/agentes_/$id'
    | '/_authenticated/app/campanhas_/$id'
    | '/_authenticated/app/campanhas_/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contatos': {
      id: '/_authenticated/app/contatos'
      path: '/contatos'
      fullPath: '/app/contatos'
      preLoaderRoute: typeof AuthenticatedAppContatosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas': {
      id: '/_authenticated/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AuthenticatedAppCampanhasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agentes': {
      id: '/_authenticated/app/agentes'
      path: '/agentes'
      fullPath: '/app/agentes'
      preLoaderRoute: typeof AuthenticatedAppAgentesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas_/nova': {
      id: '/_authenticated/app/campanhas_/nova'
      path: '/campanhas/nova'
      fullPath: '/app/campanhas/nova'
      preLoaderRoute: typeof AuthenticatedAppCampanhasNovaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campanhas_/$id': {
      id: '/_authenticated/app/campanhas_/$id'
      path: '/campanhas/$id'
      fullPath: '/app/campanhas/$id'
      preLoaderRoute: typeof AuthenticatedAppCampanhasIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agentes_/$id': {
      id: '/_authenticated/app/agentes_/$id'
      path: '/agentes/$id'
      fullPath: '/app/agentes/$id'
      preLoaderRoute: typeof AuthenticatedAppAgentesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgentesRoute: typeof AuthenticatedAppAgentesRoute
  AuthenticatedAppCampanhasRoute: typeof AuthenticatedAppCampanhasRoute
  AuthenticatedAppContatosRoute: typeof AuthenticatedAppContatosRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAgentesIdRoute: typeof AuthenticatedAppAgentesIdRoute
  AuthenticatedAppCampanhasIdRoute: typeof AuthenticatedAppCampanhasIdRoute
  AuthenticatedAppCampanhasNovaRoute: typeof AuthenticatedAppCampanhasNovaRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgentesRoute: AuthenticatedAppAgentesRoute,
  AuthenticatedAppCampanhasRoute: AuthenticatedAppCampanhasRoute,
  AuthenticatedAppContatosRoute: AuthenticatedAppContatosRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAgentesIdRoute: AuthenticatedAppAgentesIdRoute,
  AuthenticatedAppCampanhasIdRoute: AuthenticatedAppCampanhasIdRoute,
  AuthenticatedAppCampanhasNovaRoute: AuthenticatedAppCampanhasNovaRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
